version: "3"
services:
  e-commerce:
    container_name: e-commerce
    restart: always
    image: e-commerce
    build:
      context: ../
      dockerfile: ./E-COMMERCE/Dockerfile
    env_file:
      - ./.env
    networks:
      - network
    ports:
      - 3052:3052
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

networks:
  network:
