@url_dev=http://localhost:3052/v1/api

### signup 
# @name signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 89540ee863ddc282206c76ae86293c6c9e813e1f31244c0415a92842d9aacd060154457a3dd25d6b844428c96a42393ebc8c8815570e97a38dc275813aeb9943

{
    "name": "Shop TIPS",
    "email": "shoptipjs2@gmail.com",
    "password": "abc123"
}

### login 
# @name login
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: 89540ee863ddc282206c76ae86293c6c9e813e1f31244c0415a92842d9aacd060154457a3dd25d6b844428c96a42393ebc8c8815570e97a38dc275813aeb9943

{
    "email": "shoptipjs2@gmail.com",
    "password": "abc123",
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE4NzMyYzhhNmQxOGU0NjMyYzU1YzQiLCJlbWFpbCI6InNob3B0aXBqc0BnbWFpbC5jb20iLCJpYXQiOjE2OTYxNjA3NDQsImV4cCI6MTY5Njc2NTU0NH0.C8xJY4FzQ7Bt-RiDE8yOS32OmRUTzae1mCT4b0ErTdw"
}
###
@accessToken = {{login.response.body.metadata.tokens.accessToken}}
@refreshToken = {{login.response.body.metadata.tokens.refreshToken}}

### logout
# @name logout
POST {{url_dev}}/shop/logout
Content-Type: application/json
x-api-key: 89540ee863ddc282206c76ae86293c6c9e813e1f31244c0415a92842d9aacd060154457a3dd25d6b844428c96a42393ebc8c8815570e97a38dc275813aeb9943
x-client-id: 6519c6772c83a181045432ee
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE4NzMyYzhhNmQxOGU0NjMyYzU1YzQiLCJlbWFpbCI6InNob3B0aXBqc0BnbWFpbC5jb20iLCJpYXQiOjE2OTYxNjA0ODgsImV4cCI6MTY5NjMzMzI4OH0.5YY9p3J2Ea4mMje8Oo0t5m8XoWTjcjC1HQVnOiEa-bY

{}

### handlerRefreshToken
# @name handlerRefreshToken
POST {{url_dev}}/shop/handlerRefreshToken
Content-Type: application/json
x-api-key: 89540ee863ddc282206c76ae86293c6c9e813e1f31244c0415a92842d9aacd060154457a3dd25d6b844428c96a42393ebc8c8815570e97a38dc275813aeb9943
x-client-id: 6519c6772c83a181045432ee
x-rtoken-id: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE5YzY3NzJjODNhMTgxMDQ1NDMyZWUiLCJlbWFpbCI6InNob3B0aXBqc0BnbWFpbC5jb20iLCJpYXQiOjE2OTYyMzQ1OTcsImV4cCI6MTY5NjgzOTM5N30.HdtaNUufzbcejSKmN4V2FbK2gVtfyTT3QWpNY5EeL-o

{}

###
####################################################################################################################################################################################################################################
#################################################  Discount  ########################################################################################################################################################################
####################################################################################################################################################################################################################################
###

### create Discount Code
# @name createDiscountCode
POST {{url_dev}}/discount
Content-Type: application/json
x-api-key: 89540ee863ddc282206c76ae86293c6c9e813e1f31244c0415a92842d9aacd060154457a3dd25d6b844428c96a42393ebc8c8815570e97a38dc275813aeb9943
x-client-id: 652449fae10331a37dbb7e9e
authorization: {{accessToken}}

{
    "name": "name3",
    "description": "description",
    "type": "percentage",
    "value": 10,
    "max_value": 30000,
    "code": "SHOP-1122",
    "start_date": "2023-10-08 09:00:00",
    "end_date": "2023-11-08 09:00:00",
    "max_uses": 100,
    "uses_count": 0,
    "users_used": [],
    "max_uses_per_user": 1,
    "min_order_value": 200000,
    "created_by": {},
    "is_active": true,
    "product_ids": ["65210e31443a6da4f8923318"],
    "applies_to": "all"
}

### get All Discount Codes With Products
# @name getAllDiscountCodesWithProducts
GET {{url_dev}}/discount/list_product_code?code=SHOP-1133&shopId=6519c6772c83a181045432ee&limit=50&page=1
Content-Type: application/json
x-api-key: 89540ee863ddc282206c76ae86293c6c9e813e1f31244c0415a92842d9aacd060154457a3dd25d6b844428c96a42393ebc8c8815570e97a38dc275813aeb9943

{
}

### get All Discount Codes
# @name getAllDiscountCodes
GET {{url_dev}}/discount?shopId=6519c6772c83a181045432ee&limit=50&page=1
Content-Type: application/json
x-api-key: 89540ee863ddc282206c76ae86293c6c9e813e1f31244c0415a92842d9aacd060154457a3dd25d6b844428c96a42393ebc8c8815570e97a38dc275813aeb9943
x-client-id: 6519c6772c83a181045432ee
authorization: {{accessToken}}

{
}

### get All Discount Codes
# @name getAllDiscountCodes
POST {{url_dev}}/discount/amount
Content-Type: application/json
x-api-key: 89540ee863ddc282206c76ae86293c6c9e813e1f31244c0415a92842d9aacd060154457a3dd25d6b844428c96a42393ebc8c8815570e97a38dc275813aeb9943

{
    "codeId": "SHOP-1122",
    "userId": "2",
    "shopId": "6519c6772c83a181045432ee",
    "products": [{
        "productId": "65210e31443a6da4f8923318",
        "quantity": 5,
        "price": 120000
    }]
}
